# Generated by Django 6.0.6 on 2026-06-19 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('building', 'Building'), ('floor', 'Floor'), ('department', 'Department')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='operations.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('clean', 'Clean'), ('dirty', 'Dirty'), ('in_progress', 'In Progress'), ('pending_verification', 'Pending Verification'), ('overdue', 'Overdue')], default='dirty', max_length=30)),
                ('qr_code', models.CharField(max_length=50, unique=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='operations.location')),
            ],
            options={
                'ordering': ['building', 'floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('cleaner', models.ForeignKey(limit_choices_to={'role': 'cleaner'}, on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='operations.room')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_verification', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('re_cleaning', 'Re-cleaning')], default='assigned', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('before_photo', models.ImageField(blank=True, null=True, upload_to='task_photos/before/')),
                ('after_photo', models.ImageField(blank=True, null=True, upload_to='task_photos/after/')),
                ('rejection_reason', models.TextField(blank=True)),
                ('supervisor_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gps_start_lat', models.FloatField(blank=True, null=True)),
                ('gps_start_lng', models.FloatField(blank=True, null=True)),
                ('gps_start_accuracy', models.FloatField(blank=True, null=True)),
                ('gps_complete_lat', models.FloatField(blank=True, null=True)),
                ('gps_complete_lng', models.FloatField(blank=True, null=True)),
                ('gps_complete_accuracy', models.FloatField(blank=True, null=True)),
                ('qr_verified', models.BooleanField(default=False)),
                ('estimated_duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tasks', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='operations.room')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='operations.roomassignment')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('leave', 'Leave')], default='absent', max_length=20)),
                ('gps_check_in_lat', models.FloatField(blank=True, null=True)),
                ('gps_check_in_lng', models.FloatField(blank=True, null=True)),
                ('gps_check_in_accuracy', models.FloatField(blank=True, null=True)),
                ('gps_check_out_lat', models.FloatField(blank=True, null=True)),
                ('gps_check_out_lng', models.FloatField(blank=True, null=True)),
                ('gps_check_out_accuracy', models.FloatField(blank=True, null=True)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('cleaner', 'date')},
            },
        ),
    ]
